universe = vanilla
Executable     =  el8_wrapper.sh
#Should_Transfer_Files     = YES
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
Notification     = never
transfer_input_files = x509up_user.pem
#request_cpus = 1
#request_memory = 2000
#max_materialize = 5000
#+MaxRuntime = 20000

Output     = condor/log_$(Cluster).$(Process).out 
Error      = condor/log_$(Cluster).$(Process).err
Log        = condor/log_$(Cluster).$(Process).log

arguments = $(Cluster) $(Process)

queue 231
